# Generated by Django 5.1.4 on 2025-01-22 07:25

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('materials', 'Category')
    categories = ['Main','Technology','Business','Science','Health','Politics','Art',  'Sports', ]
    for category_name in categories:
        Category.objects.create(name=category_name)

class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
    ]
