# Generated by Django 5.1.4 on 2025-01-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_vocabulary_user_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('summary_english', models.TextField(blank=True, null=True)),
                ('summary_korean', models.TextField(blank=True, null=True)),
                ('url', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='accounts.category')),
                ('vocab', models.ManyToManyField(related_name='news_vocab', to='accounts.vocabulary')),
            ],
        ),
    ]
