# Generated by Django 5.1.4 on 2025-01-22 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('materials', '0001_create_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('summary_english', models.TextField(blank=True, null=True)),
                ('summary_korean', models.TextField(blank=True, null=True)),
                ('vocab', models.JSONField(blank=True, default=dict)),
                ('url', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='accounts.category')),
            ],
        ),
    ]
