# Generated by Django 5.1.4 on 2025-01-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_default_social_provider'),
        ('materials', '0002_remove_news_content_news_abstract_news_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(),
        ),
    ]
