# Generated by Django 5.1.4 on 2025-01-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_news_category_alter_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
        migrations.AddField(
            model_name='news',
            name='summary_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_korean',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='vocab',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
