# Generated by Django 5.1.4 on 2025-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_news_summary_english_news_summary_korean_news_vocab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
