# Generated by Django 5.1.4 on 2025-01-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_customsocialaccount_delete_socialaccount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customsocialaccount',
            unique_together={('provider', 'uid')},
        ),
    ]
