# Generated by Django 5.1.4 on 2025-01-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_alter_customsocialaccount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsocialaccount',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
