# Generated by Django 5.1.4 on 2025-01-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_birthday_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected_social_providers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='is_social_connected',
            field=models.BooleanField(default=False),
        ),
    ]
