# Generated by Django 5.1.4 on 2025-01-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_category_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_social_provider',
            field=models.CharField(blank=True, help_text='사용자가 기사를 받을 소셜 계정 provider', max_length=50, null=True),
        ),
    ]
