# Generated by Django 5.1.4 on 2025-01-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_default_social_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='source_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
