# Generated by Django 5.1.4 on 2025-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_category_source_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messenger_platform',
            field=models.CharField(blank=True, choices=[('kakao', '카카오톡'), ('discord', '디스코드드')], max_length=20, null=True),
        ),
    ]
