# Generated by Django 5.1.4 on 2025-01-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_messenger_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messenger_platform',
        ),
    ]
