# Generated by Django 5.1.4 on 2025-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.JSONField(blank=True, default=dict, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='vocabulary',
            field=models.ManyToManyField(default=dict, to='accounts.vocabulary'),
        ),
    ]
